name = "PingpongLeaqueChat"
uuid = "cb12629b-27c4-4207-a2c6-cead23094a12"
authors = ["daryoush mehrtash"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
